<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PNGD1263" ignored="0" name="Test" tests="4" failures="2" timestamp="25 Jan 2019 08:36:56 GMT" time="209.845" errors="0">
  <testcase name="Scenario_1" time="60.691" classname="restAPIFramework.api.test.TestCase"/>
  <testcase name="Scenario_2" time="58.735" classname="restAPIFramework.api.test.TestCase"/>
  <testcase name="Scenario_3" time="45.033" classname="restAPIFramework.api.test.TestCase">
    <failure type="java.lang.AssertionError" message="expected [Completed] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Completed] but found [Failure]
	at restAPIFramework.api.test.TestCase.Scenario_3(TestCase.java:217)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Scenario_3 -->
  <testcase name="Scenario_4" time="45.349" classname="restAPIFramework.api.test.TestCase">
    <failure type="java.lang.AssertionError" message="expected [Completed] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Completed] but found [Failure]
	at restAPIFramework.api.test.TestCase.Scenario_4(TestCase.java:285)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Scenario_4 -->
</testsuite> <!-- Test -->
